### ISSUE TITLE
It's working but how to edit /vendor/build.gradle

### ISSUE THREAD

**Issue by Bobur-777** [araafroyall/Systemless-build.prop#4]
Hello. I need to edit idle.default.fps value from /vendor/build.gradle but I can't edit it. Pease help me

**Comment by araafroyall** [comment]
> Hello. I need to edit idle.default.fps value from /vendor/build.gradle but I can't edit it. Pease help me

You can use Material file manager and locate build.gradle than edit with root acess. 

Sorry for late reply. i will also look upon this in upcoming updates. Thanks 👍

**Comment by araafroyall** [comment]
> Hello. I need to edit idle.default.fps value from /vendor/build.gradle but I can't edit it. Pease help me

Hi. i started making Systemless build.prop and which will take about 2 more days to completed.

i found /system/vendor/build.prop or vendor/build.prop

but i dont find build.gradle , can you send me its Exact Location or Path so i can look upon this.
