### ISSUE TITLE
command fails to execute

### ISSUE THREAD

**Issue by mikalueh** [araafroyall/Systemless-build.prop#7]
Hi! I rooted my phone with Magisk and installed your module. Of course I rebooted after the install. But wether I use the command with or without root privileges in termux; it gives me the error message "Bad system call" when I try to see the error report using the dmesg command.

What I tried:
`setprop ro.debuggable 1`

What I got as a response:
`Failed to set property ro.debuggable to 1. See dmesg for error reason`

dmesg output:
`Bad system call`

**Comment by araafroyall** [comment]
> Hi! I rooted my phone with Magisk and installed your module. Of course I rebooted after the install. But wether I use the command with or without root privileges in termux; it gives me the error message "Bad system call" when I try to see the error report using the dmesg command.
> 
> What I tried:
> `setprop ro.debuggable 1`
> 
> What I got as a response:
> `Failed to set property ro.debuggable to 1. See dmesg for error reason`
> 
> dmesg output:
> `Bad system call`
> 

Brother this is not a problem of my module. Its your system not allowing to change prop data.

You can try Alternative method.
use material file manager than go to /system/build.prop than add or edit line as "ro.debuggable=1"

Hope you understand
